# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(build_number: number_of_commits)
    build_app(workspace: "dimigoin.xcworkspace", scheme: "dimigoin")
    upload_to_testflight
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :versionBump do
    increment_build_number(build_number: number_of_commits)
    commit_version_bump(xcodeproj: "dimigoin.xcodeproj")
    add_git_tag
    push_to_git_remote
  end
end

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots
    frame_screenshots
  end
end

platform :ios do
  desc "release - only build"
  lane :release do 
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "dimigoin")
    upload_to_app_store                  # upload your app to App Store Connect
  end
end


platform :ios do
  desc "Deploy new build to AppStore"
  lane :deploy do 
    capture_screenshots
    frame_screenshots
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "dimigoin")
    upload_to_app_store                  # upload your app to App Store Connect
  end
end


